version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: gubee-postgres
    environment:
      POSTGRES_DB: stock_reconciliation
      POSTGRES_USER: gubee
      POSTGRES_PASSWORD: gubee
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    container_name: gubee-redis
    ports:
      - "6379:6379"